### PR TITLE
fix priority ranking

### PR DESCRIPTION
**Pull request by haoxianhan**
if `_build` dir is exist, other such as `apps` tags' priority would
    less-than `_build`'s, but it don't want to jump `_build` in general,
    so hard code `_build` priority to be lower.
it's hotfix for me, clean up the code if necessary.

### CODE REVIEW

**Comment by hcs42** [comment]
Hi @haoxianhan,

Thank you for your contribution.

I modified your commit: <https://github.com/hcs42/vim-erlang-tags/commits/build_dir_priority>

- I made sure that the code conforms to <https://github.com/vim-erlang/vim-erlang#contributing>. (Every new function has a docstring and a typespec, the lines are not longer than 80 characters, etc).
- I added automatic tests (see <https://github.com/hcs42/vim-erlang/commits/build_dir_priority>)
- I removed the temporary ETS table (and instead modified the code to the perform sorting on the Erlang representation of the tags, rather than the binary output lines).
- Previously your fix worked only if you were in the same directory where the `_build` directory was (because of the `string:prefix` call). The modified commit recognizes `_build` directories even if you are not in its parent directory.
- My other reason for replacing `string:prefix` with `re:run` is that `string:prefix` was introduced in OTP 20, and I would like to keep vim-erlang working with older Erlang versions. (E.g., it even works on OTP R16B03.)

Could you test the modified commit?

Out of curiosity: do you use Windows?

**Comment by haoxianhan** [comment]
wow, my pleasure, I would test this branch these days.
I use is archlinux for my dev environment, ssh remote by win10.

**Comment by haoxianhan** [comment]
I use the `build_dir_priority` branch for few days, it works fine.
Furthermore, I've compared the `tags` to my `hotfix`'s, it's more appropriate.

**Comment by hcs42** [comment]
I merged the commits.

**Pull request closed without merging**
