### PR TITLE
Put functions not needed at startup under autoload

### PR DESCRIPTION
**Pull request by slarwise**
Done to decrease startup time

### CODE REVIEW

**Comment by hcs42** [comment]
Thanks!

Out of curiosity: have you performed any measurements about how much this decreases startup time?

**Comment by slarwise** [comment]
Awesome, thanks 😃

At work I had to use Vim 7.4 on a pretty slow computer and sourcing plugin/vim-erlang-tags.vim took about 300 ms. After moving the functions to autoload it took less than 1 ms to source. So it was nice when I was gonna use Vim for something else than Erlang.

On my macbook pro 2017 with a newer vim version the difference is not as noticeable. For neovim 0.4.3 it took about 20 ms without autoload and 0.06 ms with and about the same for vim 8.2.

**Comment by hcs42** [comment]
Thanks for the info :)

**Comment by slarwise** [comment]
No problem, thanks for the awesome plugin :)

**Pull request merged**
